# Generated by Django 5.0.1 on 2024-02-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_logger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
    ]
